

# This file was *autogenerated* from the file testing_index.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from index import *

gens = [
    matrix([[_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ]]),
    matrix([[_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_1 ]])
]

print(is_finite_index(gens))

